name='This Provider'
provider_name='{{ "airflow-provider-" ~ name | lower | replace(from=" ", to="-") }}'
provider_slug='{{ provider_name | replace(from=" ", to="_") | replace(from="-", to="_") }}'
airflow_version='2.5.0'
author_name='Osborne Reynolds'
author_email='osborne.reynolds@airflow.com'
short_description='A short description of the package'